#define NORMAL_SUCCESS           0
#define UNKNOWN_FAIL            -1
#define THREAD_FAIL             -2
#define SOCKET_FAIL             -3
#define BIND_FAIL               -4
#define ACCEPT_FAIL             -5
#define ALREADY_RUNNING_FAIL    -6
#define ALREADY_STOPPED_FAIL    -7
#define UNKNOWN_IP_FAIL         -8
#define CONNECT_FAIL            -9
#define RECV_FAIL               -10
